sub1=int(input("Enter the marks of first subject: "))
sub2=int(input("Enter the marks of second subject: "))
sub3=int(input("Enter the marks of third subject: "))
sub4=int(input("Enter the marks of fourth subject: "))
sub5=int(input("Enter the marks of fifth subject: "))
print("Total marks: ",sub1+sub2+sub3+sub4+sub5)
print("Average marks: ",(sub1+sub2+sub3+sub4+sub5)/5)